#ifndef __CRouterListPanel__
#define __CRouterListPanel__

/**
@file
Subclass of CRouterListPanelBase, which is generated by wxFormBuilder.
*/

#include "AlcatelMetro.h"

//// end generated include

/** Implementing CRouterListPanelBase */
class CRouterListPanel : public CRouterListPanelBase
{
	public:
		/** Constructor */
		CRouterListPanel( wxWindow* parent, wxWindowID id, const wxPoint& pos, const wxSize& size, long style);

	//// end generated class members
	
};

#endif // __CRouterListPanel__
