#ifndef __CTerminalViewPanel__
#define __CTerminalViewPanel__

/**
@file
Subclass of CTerminalViewPanelBase, which is generated by wxFormBuilder.
*/

#include "AlcatelMetro.h"

//// end generated include

/** Implementing CTerminalViewPanelBase */
class CTerminalViewPanel : public CTerminalViewPanelBase
{
	public:
		/** Constructor */
		CTerminalViewPanel( wxWindow* parent, wxWindowID id, const wxPoint& pos, const wxSize& size, long style );
	//// end generated class members
	
};

#endif // __CTerminalViewPanel__
