#ifndef __CTopologyViewPanel__
#define __CTopologyViewPanel__

/**
@file
Subclass of CTopologyViewPanelBase, which is generated by wxFormBuilder.
*/

#include "AlcatelMetro.h"

//// end generated include

/** Implementing CTopologyViewPanelBase */
class CTopologyViewPanel : public CTopologyViewPanelBase
{
	public:
		/** Constructor */
		CTopologyViewPanel( wxWindow* parent, wxWindowID id, const wxPoint& pos, const wxSize& size, long style );
	//// end generated class members
	
};

#endif // __CTopologyViewPanel__
